# Generated by Django 2.0.1 on 2018-01-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField(default=0)),
                ('row0', models.CharField(max_length=10, null=True)),
                ('row1', models.CharField(max_length=10, null=True)),
                ('row2', models.CharField(max_length=8, null=True)),
                ('row3', models.CharField(max_length=10, null=True)),
                ('row4', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'player_board',
            },
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('bool', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'player_info',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('speed', models.IntegerField(default=20)),
                ('players', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.Rooms'),
        ),
        migrations.AddField(
            model_name='playerboard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.PlayerInfo'),
        ),
    ]
