# Generated by Django 2.0.1 on 2018-01-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Rooms')),
            ],
        ),
    ]
