# Generated by Django 2.0.1 on 2018-01-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='room_id',
            new_name='room',
        ),
    ]
